// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: inference.proto

package inferencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceService_GenerateMedia_FullMethodName    = "/maestro.inference.v1.InferenceService/GenerateMedia"
	InferenceService_CancelGeneration_FullMethodName = "/maestro.inference.v1.InferenceService/CancelGeneration"
	InferenceService_TranscribeAudio_FullMethodName  = "/maestro.inference.v1.InferenceService/TranscribeAudio"
	InferenceService_EnhancePrompt_FullMethodName    = "/maestro.inference.v1.InferenceService/EnhancePrompt"
	InferenceService_GetGpuTelemetry_FullMethodName  = "/maestro.inference.v1.InferenceService/GetGpuTelemetry"
	InferenceService_ListModels_FullMethodName       = "/maestro.inference.v1.InferenceService/ListModels"
)

// InferenceServiceClient is the client API for InferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceServiceClient interface {
	// Streaming de progreso de generación de video/imagen
	GenerateMedia(ctx context.Context, in *MediaGenerationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerationProgressResponse], error)
	// Cancelar una generación en curso
	CancelGeneration(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// Transcripción y análisis de audio
	TranscribeAudio(ctx context.Context, in *AudioTranscriptionRequest, opts ...grpc.CallOption) (*TranscriptionResponse, error)
	// Mejora de prompts con LLM local
	EnhancePrompt(ctx context.Context, in *PromptEnhanceRequest, opts ...grpc.CallOption) (*PromptEnhanceResponse, error)
	// Estado y telemetría de GPU / VRAM
	GetGpuTelemetry(ctx context.Context, in *GpuTelemetryRequest, opts ...grpc.CallOption) (*GpuTelemetryResponse, error)
	// Catálogo de modelos disponibles (motores, VRAM, disponibilidad)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) GenerateMedia(ctx context.Context, in *MediaGenerationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerationProgressResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceService_ServiceDesc.Streams[0], InferenceService_GenerateMedia_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MediaGenerationRequest, GenerationProgressResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceService_GenerateMediaClient = grpc.ServerStreamingClient[GenerationProgressResponse]

func (c *inferenceServiceClient) CancelGeneration(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, InferenceService_CancelGeneration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) TranscribeAudio(ctx context.Context, in *AudioTranscriptionRequest, opts ...grpc.CallOption) (*TranscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TranscriptionResponse)
	err := c.cc.Invoke(ctx, InferenceService_TranscribeAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) EnhancePrompt(ctx context.Context, in *PromptEnhanceRequest, opts ...grpc.CallOption) (*PromptEnhanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PromptEnhanceResponse)
	err := c.cc.Invoke(ctx, InferenceService_EnhancePrompt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) GetGpuTelemetry(ctx context.Context, in *GpuTelemetryRequest, opts ...grpc.CallOption) (*GpuTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GpuTelemetryResponse)
	err := c.cc.Invoke(ctx, InferenceService_GetGpuTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, InferenceService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceServiceServer is the server API for InferenceService service.
// All implementations must embed UnimplementedInferenceServiceServer
// for forward compatibility.
type InferenceServiceServer interface {
	// Streaming de progreso de generación de video/imagen
	GenerateMedia(*MediaGenerationRequest, grpc.ServerStreamingServer[GenerationProgressResponse]) error
	// Cancelar una generación en curso
	CancelGeneration(context.Context, *CancelRequest) (*CancelResponse, error)
	// Transcripción y análisis de audio
	TranscribeAudio(context.Context, *AudioTranscriptionRequest) (*TranscriptionResponse, error)
	// Mejora de prompts con LLM local
	EnhancePrompt(context.Context, *PromptEnhanceRequest) (*PromptEnhanceResponse, error)
	// Estado y telemetría de GPU / VRAM
	GetGpuTelemetry(context.Context, *GpuTelemetryRequest) (*GpuTelemetryResponse, error)
	// Catálogo de modelos disponibles (motores, VRAM, disponibilidad)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	mustEmbedUnimplementedInferenceServiceServer()
}

// UnimplementedInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServiceServer struct{}

func (UnimplementedInferenceServiceServer) GenerateMedia(*MediaGenerationRequest, grpc.ServerStreamingServer[GenerationProgressResponse]) error {
	return status.Error(codes.Unimplemented, "method GenerateMedia not implemented")
}
func (UnimplementedInferenceServiceServer) CancelGeneration(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelGeneration not implemented")
}
func (UnimplementedInferenceServiceServer) TranscribeAudio(context.Context, *AudioTranscriptionRequest) (*TranscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TranscribeAudio not implemented")
}
func (UnimplementedInferenceServiceServer) EnhancePrompt(context.Context, *PromptEnhanceRequest) (*PromptEnhanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnhancePrompt not implemented")
}
func (UnimplementedInferenceServiceServer) GetGpuTelemetry(context.Context, *GpuTelemetryRequest) (*GpuTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGpuTelemetry not implemented")
}
func (UnimplementedInferenceServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedInferenceServiceServer) mustEmbedUnimplementedInferenceServiceServer() {}
func (UnimplementedInferenceServiceServer) testEmbeddedByValue()                          {}

// UnsafeInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServiceServer will
// result in compilation errors.
type UnsafeInferenceServiceServer interface {
	mustEmbedUnimplementedInferenceServiceServer()
}

func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_GenerateMedia_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MediaGenerationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceServiceServer).GenerateMedia(m, &grpc.GenericServerStream[MediaGenerationRequest, GenerationProgressResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceService_GenerateMediaServer = grpc.ServerStreamingServer[GenerationProgressResponse]

func _InferenceService_CancelGeneration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).CancelGeneration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_CancelGeneration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).CancelGeneration(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_TranscribeAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AudioTranscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).TranscribeAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_TranscribeAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).TranscribeAudio(ctx, req.(*AudioTranscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_EnhancePrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromptEnhanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).EnhancePrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_EnhancePrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).EnhancePrompt(ctx, req.(*PromptEnhanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_GetGpuTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GpuTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).GetGpuTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_GetGpuTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).GetGpuTelemetry(ctx, req.(*GpuTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceService_ServiceDesc is the grpc.ServiceDesc for InferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "maestro.inference.v1.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelGeneration",
			Handler:    _InferenceService_CancelGeneration_Handler,
		},
		{
			MethodName: "TranscribeAudio",
			Handler:    _InferenceService_TranscribeAudio_Handler,
		},
		{
			MethodName: "EnhancePrompt",
			Handler:    _InferenceService_EnhancePrompt_Handler,
		},
		{
			MethodName: "GetGpuTelemetry",
			Handler:    _InferenceService_GetGpuTelemetry_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _InferenceService_ListModels_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GenerateMedia",
			Handler:       _InferenceService_GenerateMedia_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inference.proto",
}
