// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`     // "image" | "video" | "tts" | "audio"
	Engine        string                 `protobuf:"bytes,4,opt,name=engine,proto3" json:"engine,omitempty"` // "diffusers" | "v1_bridge" | "mock"
	Pipeline      string                 `protobuf:"bytes,5,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Repo          string                 `protobuf:"bytes,6,opt,name=repo,proto3" json:"repo,omitempty"`
	Steps         int32                  `protobuf:"varint,7,opt,name=steps,proto3" json:"steps,omitempty"`
	VramGb        int32                  `protobuf:"varint,8,opt,name=vram_gb,json=vramGb,proto3" json:"vram_gb,omitempty"`
	Family        string                 `protobuf:"bytes,9,opt,name=family,proto3" json:"family,omitempty"`
	Available     bool                   `protobuf:"varint,10,opt,name=available,proto3" json:"available,omitempty"` // false si requiere volumen V1 no montado
	Notes         string                 `protobuf:"bytes,11,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *ModelInfo) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ModelInfo) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ModelInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ModelInfo) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *ModelInfo) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *ModelInfo) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

func (x *ModelInfo) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *ModelInfo) GetVramGb() int32 {
	if x != nil {
		return x.VramGb
	}
	return 0
}

func (x *ModelInfo) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *ModelInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ModelInfo) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	DeviceName    string                 `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	CudaAvailable bool                   `protobuf:"varint,3,opt,name=cuda_available,json=cudaAvailable,proto3" json:"cuda_available,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

func (x *ListModelsResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *ListModelsResponse) GetCudaAvailable() bool {
	if x != nil {
		return x.CudaAvailable
	}
	return false
}

type MediaGenerationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Mode           string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"` // "video" o "image"
	ModelName      string                 `protobuf:"bytes,3,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Prompt         string                 `protobuf:"bytes,4,opt,name=prompt,proto3" json:"prompt,omitempty"`
	NegativePrompt string                 `protobuf:"bytes,5,opt,name=negative_prompt,json=negativePrompt,proto3" json:"negative_prompt,omitempty"`
	Width          int32                  `protobuf:"varint,6,opt,name=width,proto3" json:"width,omitempty"`
	Height         int32                  `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	NumFrames      int32                  `protobuf:"varint,8,opt,name=num_frames,json=numFrames,proto3" json:"num_frames,omitempty"`
	Fps            int32                  `protobuf:"varint,9,opt,name=fps,proto3" json:"fps,omitempty"`
	Steps          int32                  `protobuf:"varint,10,opt,name=steps,proto3" json:"steps,omitempty"`
	CfgScale       float32                `protobuf:"fixed32,11,opt,name=cfg_scale,json=cfgScale,proto3" json:"cfg_scale,omitempty"`
	Seed           int64                  `protobuf:"varint,12,opt,name=seed,proto3" json:"seed,omitempty"`
	Loras          []*LoraConfig          `protobuf:"bytes,13,rep,name=loras,proto3" json:"loras,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaGenerationRequest) Reset() {
	*x = MediaGenerationRequest{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaGenerationRequest) ProtoMessage() {}

func (x *MediaGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaGenerationRequest.ProtoReflect.Descriptor instead.
func (*MediaGenerationRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *MediaGenerationRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MediaGenerationRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *MediaGenerationRequest) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *MediaGenerationRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *MediaGenerationRequest) GetNegativePrompt() string {
	if x != nil {
		return x.NegativePrompt
	}
	return ""
}

func (x *MediaGenerationRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaGenerationRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaGenerationRequest) GetNumFrames() int32 {
	if x != nil {
		return x.NumFrames
	}
	return 0
}

func (x *MediaGenerationRequest) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *MediaGenerationRequest) GetSteps() int32 {
	if x != nil {
		return x.Steps
	}
	return 0
}

func (x *MediaGenerationRequest) GetCfgScale() float32 {
	if x != nil {
		return x.CfgScale
	}
	return 0
}

func (x *MediaGenerationRequest) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *MediaGenerationRequest) GetLoras() []*LoraConfig {
	if x != nil {
		return x.Loras
	}
	return nil
}

type LoraConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Weight        float32                `protobuf:"fixed32,3,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoraConfig) Reset() {
	*x = LoraConfig{}
	mi := &file_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoraConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoraConfig) ProtoMessage() {}

func (x *LoraConfig) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoraConfig.ProtoReflect.Descriptor instead.
func (*LoraConfig) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4}
}

func (x *LoraConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoraConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *LoraConfig) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type GenerationProgressResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	JobId          string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	CurrentStep    int32                  `protobuf:"varint,2,opt,name=current_step,json=currentStep,proto3" json:"current_step,omitempty"`
	TotalSteps     int32                  `protobuf:"varint,3,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	Percentage     float32                `protobuf:"fixed32,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	EtaSeconds     string                 `protobuf:"bytes,5,opt,name=eta_seconds,json=etaSeconds,proto3" json:"eta_seconds,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                                    // "LOADING_MODEL", "GENERATING", "POSTPROCESSING", "COMPLETED", "FAILED", "CANCELLED"
	PreviewBase64  string                 `protobuf:"bytes,7,opt,name=preview_base64,json=previewBase64,proto3" json:"preview_base64,omitempty"` // Frame de preview opcional
	OutputFilePath string                 `protobuf:"bytes,8,opt,name=output_file_path,json=outputFilePath,proto3" json:"output_file_path,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerationProgressResponse) Reset() {
	*x = GenerationProgressResponse{}
	mi := &file_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationProgressResponse) ProtoMessage() {}

func (x *GenerationProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationProgressResponse.ProtoReflect.Descriptor instead.
func (*GenerationProgressResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{5}
}

func (x *GenerationProgressResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GenerationProgressResponse) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *GenerationProgressResponse) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *GenerationProgressResponse) GetPercentage() float32 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *GenerationProgressResponse) GetEtaSeconds() string {
	if x != nil {
		return x.EtaSeconds
	}
	return ""
}

func (x *GenerationProgressResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerationProgressResponse) GetPreviewBase64() string {
	if x != nil {
		return x.PreviewBase64
	}
	return ""
}

func (x *GenerationProgressResponse) GetOutputFilePath() string {
	if x != nil {
		return x.OutputFilePath
	}
	return ""
}

func (x *GenerationProgressResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Accepted      bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"` // false si el job no está activo en el worker
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{7}
}

func (x *CancelResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type AudioTranscriptionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioPath     string                 `protobuf:"bytes,1,opt,name=audio_path,json=audioPath,proto3" json:"audio_path,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Diarization   bool                   `protobuf:"varint,3,opt,name=diarization,proto3" json:"diarization,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioTranscriptionRequest) Reset() {
	*x = AudioTranscriptionRequest{}
	mi := &file_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioTranscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioTranscriptionRequest) ProtoMessage() {}

func (x *AudioTranscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioTranscriptionRequest.ProtoReflect.Descriptor instead.
func (*AudioTranscriptionRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{8}
}

func (x *AudioTranscriptionRequest) GetAudioPath() string {
	if x != nil {
		return x.AudioPath
	}
	return ""
}

func (x *AudioTranscriptionRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *AudioTranscriptionRequest) GetDiarization() bool {
	if x != nil {
		return x.Diarization
	}
	return false
}

type TranscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Bpm           float32                `protobuf:"fixed32,2,opt,name=bpm,proto3" json:"bpm,omitempty"`
	Segments      []*AudioSegment        `protobuf:"bytes,3,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptionResponse) Reset() {
	*x = TranscriptionResponse{}
	mi := &file_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptionResponse) ProtoMessage() {}

func (x *TranscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptionResponse.ProtoReflect.Descriptor instead.
func (*TranscriptionResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{9}
}

func (x *TranscriptionResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptionResponse) GetBpm() float32 {
	if x != nil {
		return x.Bpm
	}
	return 0
}

func (x *TranscriptionResponse) GetSegments() []*AudioSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type AudioSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTime     float32                `protobuf:"fixed32,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       float32                `protobuf:"fixed32,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Speaker       string                 `protobuf:"bytes,3,opt,name=speaker,proto3" json:"speaker,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioSegment) Reset() {
	*x = AudioSegment{}
	mi := &file_inference_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioSegment) ProtoMessage() {}

func (x *AudioSegment) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioSegment.ProtoReflect.Descriptor instead.
func (*AudioSegment) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{10}
}

func (x *AudioSegment) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *AudioSegment) GetEndTime() float32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *AudioSegment) GetSpeaker() string {
	if x != nil {
		return x.Speaker
	}
	return ""
}

func (x *AudioSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type PromptEnhanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawPrompt     string                 `protobuf:"bytes,1,opt,name=raw_prompt,json=rawPrompt,proto3" json:"raw_prompt,omitempty"`
	TargetModel   string                 `protobuf:"bytes,2,opt,name=target_model,json=targetModel,proto3" json:"target_model,omitempty"`
	Style         string                 `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptEnhanceRequest) Reset() {
	*x = PromptEnhanceRequest{}
	mi := &file_inference_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptEnhanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptEnhanceRequest) ProtoMessage() {}

func (x *PromptEnhanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptEnhanceRequest.ProtoReflect.Descriptor instead.
func (*PromptEnhanceRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{11}
}

func (x *PromptEnhanceRequest) GetRawPrompt() string {
	if x != nil {
		return x.RawPrompt
	}
	return ""
}

func (x *PromptEnhanceRequest) GetTargetModel() string {
	if x != nil {
		return x.TargetModel
	}
	return ""
}

func (x *PromptEnhanceRequest) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

type PromptEnhanceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnhancedPrompt string                 `protobuf:"bytes,1,opt,name=enhanced_prompt,json=enhancedPrompt,proto3" json:"enhanced_prompt,omitempty"`
	Rationale      string                 `protobuf:"bytes,2,opt,name=rationale,proto3" json:"rationale,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PromptEnhanceResponse) Reset() {
	*x = PromptEnhanceResponse{}
	mi := &file_inference_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptEnhanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptEnhanceResponse) ProtoMessage() {}

func (x *PromptEnhanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptEnhanceResponse.ProtoReflect.Descriptor instead.
func (*PromptEnhanceResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{12}
}

func (x *PromptEnhanceResponse) GetEnhancedPrompt() string {
	if x != nil {
		return x.EnhancedPrompt
	}
	return ""
}

func (x *PromptEnhanceResponse) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

type GpuTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuTelemetryRequest) Reset() {
	*x = GpuTelemetryRequest{}
	mi := &file_inference_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuTelemetryRequest) ProtoMessage() {}

func (x *GpuTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuTelemetryRequest.ProtoReflect.Descriptor instead.
func (*GpuTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{13}
}

type GpuTelemetryResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceName     string                 `protobuf:"bytes,1,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	TotalVramMb    int64                  `protobuf:"varint,2,opt,name=total_vram_mb,json=totalVramMb,proto3" json:"total_vram_mb,omitempty"`
	UsedVramMb     int64                  `protobuf:"varint,3,opt,name=used_vram_mb,json=usedVramMb,proto3" json:"used_vram_mb,omitempty"`
	FreeVramMb     int64                  `protobuf:"varint,4,opt,name=free_vram_mb,json=freeVramMb,proto3" json:"free_vram_mb,omitempty"`
	GpuUtilization float32                `protobuf:"fixed32,5,opt,name=gpu_utilization,json=gpuUtilization,proto3" json:"gpu_utilization,omitempty"`
	TemperatureC   float32                `protobuf:"fixed32,6,opt,name=temperature_c,json=temperatureC,proto3" json:"temperature_c,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GpuTelemetryResponse) Reset() {
	*x = GpuTelemetryResponse{}
	mi := &file_inference_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuTelemetryResponse) ProtoMessage() {}

func (x *GpuTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuTelemetryResponse.ProtoReflect.Descriptor instead.
func (*GpuTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{14}
}

func (x *GpuTelemetryResponse) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *GpuTelemetryResponse) GetTotalVramMb() int64 {
	if x != nil {
		return x.TotalVramMb
	}
	return 0
}

func (x *GpuTelemetryResponse) GetUsedVramMb() int64 {
	if x != nil {
		return x.UsedVramMb
	}
	return 0
}

func (x *GpuTelemetryResponse) GetFreeVramMb() int64 {
	if x != nil {
		return x.FreeVramMb
	}
	return 0
}

func (x *GpuTelemetryResponse) GetGpuUtilization() float32 {
	if x != nil {
		return x.GpuUtilization
	}
	return 0
}

func (x *GpuTelemetryResponse) GetTemperatureC() float32 {
	if x != nil {
		return x.TemperatureC
	}
	return 0
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\x14maestro.inference.v1\"\x13\n" +
	"\x11ListModelsRequest\"\x8a\x02\n" +
	"\tModelInfo\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x16\n" +
	"\x06engine\x18\x04 \x01(\tR\x06engine\x12\x1a\n" +
	"\bpipeline\x18\x05 \x01(\tR\bpipeline\x12\x12\n" +
	"\x04repo\x18\x06 \x01(\tR\x04repo\x12\x14\n" +
	"\x05steps\x18\a \x01(\x05R\x05steps\x12\x17\n" +
	"\avram_gb\x18\b \x01(\x05R\x06vramGb\x12\x16\n" +
	"\x06family\x18\t \x01(\tR\x06family\x12\x1c\n" +
	"\tavailable\x18\n" +
	" \x01(\bR\tavailable\x12\x14\n" +
	"\x05notes\x18\v \x01(\tR\x05notes\"\x95\x01\n" +
	"\x12ListModelsResponse\x127\n" +
	"\x06models\x18\x01 \x03(\v2\x1f.maestro.inference.v1.ModelInfoR\x06models\x12\x1f\n" +
	"\vdevice_name\x18\x02 \x01(\tR\n" +
	"deviceName\x12%\n" +
	"\x0ecuda_available\x18\x03 \x01(\bR\rcudaAvailable\"\x81\x03\n" +
	"\x16MediaGenerationRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"model_name\x18\x03 \x01(\tR\tmodelName\x12\x16\n" +
	"\x06prompt\x18\x04 \x01(\tR\x06prompt\x12'\n" +
	"\x0fnegative_prompt\x18\x05 \x01(\tR\x0enegativePrompt\x12\x14\n" +
	"\x05width\x18\x06 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\a \x01(\x05R\x06height\x12\x1d\n" +
	"\n" +
	"num_frames\x18\b \x01(\x05R\tnumFrames\x12\x10\n" +
	"\x03fps\x18\t \x01(\x05R\x03fps\x12\x14\n" +
	"\x05steps\x18\n" +
	" \x01(\x05R\x05steps\x12\x1b\n" +
	"\tcfg_scale\x18\v \x01(\x02R\bcfgScale\x12\x12\n" +
	"\x04seed\x18\f \x01(\x03R\x04seed\x126\n" +
	"\x05loras\x18\r \x03(\v2 .maestro.inference.v1.LoraConfigR\x05loras\"L\n" +
	"\n" +
	"LoraConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\x02R\x06weight\"\xc6\x02\n" +
	"\x1aGenerationProgressResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\fcurrent_step\x18\x02 \x01(\x05R\vcurrentStep\x12\x1f\n" +
	"\vtotal_steps\x18\x03 \x01(\x05R\n" +
	"totalSteps\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x02R\n" +
	"percentage\x12\x1f\n" +
	"\veta_seconds\x18\x05 \x01(\tR\n" +
	"etaSeconds\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0epreview_base64\x18\a \x01(\tR\rpreviewBase64\x12(\n" +
	"\x10output_file_path\x18\b \x01(\tR\x0eoutputFilePath\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\"&\n" +
	"\rCancelRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"C\n" +
	"\x0eCancelResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\"x\n" +
	"\x19AudioTranscriptionRequest\x12\x1d\n" +
	"\n" +
	"audio_path\x18\x01 \x01(\tR\taudioPath\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12 \n" +
	"\vdiarization\x18\x03 \x01(\bR\vdiarization\"}\n" +
	"\x15TranscriptionResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x10\n" +
	"\x03bpm\x18\x02 \x01(\x02R\x03bpm\x12>\n" +
	"\bsegments\x18\x03 \x03(\v2\".maestro.inference.v1.AudioSegmentR\bsegments\"v\n" +
	"\fAudioSegment\x12\x1d\n" +
	"\n" +
	"start_time\x18\x01 \x01(\x02R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x02 \x01(\x02R\aendTime\x12\x18\n" +
	"\aspeaker\x18\x03 \x01(\tR\aspeaker\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"n\n" +
	"\x14PromptEnhanceRequest\x12\x1d\n" +
	"\n" +
	"raw_prompt\x18\x01 \x01(\tR\trawPrompt\x12!\n" +
	"\ftarget_model\x18\x02 \x01(\tR\vtargetModel\x12\x14\n" +
	"\x05style\x18\x03 \x01(\tR\x05style\"^\n" +
	"\x15PromptEnhanceResponse\x12'\n" +
	"\x0fenhanced_prompt\x18\x01 \x01(\tR\x0eenhancedPrompt\x12\x1c\n" +
	"\trationale\x18\x02 \x01(\tR\trationale\"\x15\n" +
	"\x13GpuTelemetryRequest\"\xed\x01\n" +
	"\x14GpuTelemetryResponse\x12\x1f\n" +
	"\vdevice_name\x18\x01 \x01(\tR\n" +
	"deviceName\x12\"\n" +
	"\rtotal_vram_mb\x18\x02 \x01(\x03R\vtotalVramMb\x12 \n" +
	"\fused_vram_mb\x18\x03 \x01(\x03R\n" +
	"usedVramMb\x12 \n" +
	"\ffree_vram_mb\x18\x04 \x01(\x03R\n" +
	"freeVramMb\x12'\n" +
	"\x0fgpu_utilization\x18\x05 \x01(\x02R\x0egpuUtilization\x12#\n" +
	"\rtemperature_c\x18\x06 \x01(\x02R\ftemperatureC2\x8a\x05\n" +
	"\x10InferenceService\x12q\n" +
	"\rGenerateMedia\x12,.maestro.inference.v1.MediaGenerationRequest\x1a0.maestro.inference.v1.GenerationProgressResponse0\x01\x12]\n" +
	"\x10CancelGeneration\x12#.maestro.inference.v1.CancelRequest\x1a$.maestro.inference.v1.CancelResponse\x12o\n" +
	"\x0fTranscribeAudio\x12/.maestro.inference.v1.AudioTranscriptionRequest\x1a+.maestro.inference.v1.TranscriptionResponse\x12h\n" +
	"\rEnhancePrompt\x12*.maestro.inference.v1.PromptEnhanceRequest\x1a+.maestro.inference.v1.PromptEnhanceResponse\x12h\n" +
	"\x0fGetGpuTelemetry\x12).maestro.inference.v1.GpuTelemetryRequest\x1a*.maestro.inference.v1.GpuTelemetryResponse\x12_\n" +
	"\n" +
	"ListModels\x12'.maestro.inference.v1.ListModelsRequest\x1a(.maestro.inference.v1.ListModelsResponseB5Z3brain-master/backend/proto/inference/v1;inferencev1b\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_inference_proto_goTypes = []any{
	(*ListModelsRequest)(nil),          // 0: maestro.inference.v1.ListModelsRequest
	(*ModelInfo)(nil),                  // 1: maestro.inference.v1.ModelInfo
	(*ListModelsResponse)(nil),         // 2: maestro.inference.v1.ListModelsResponse
	(*MediaGenerationRequest)(nil),     // 3: maestro.inference.v1.MediaGenerationRequest
	(*LoraConfig)(nil),                 // 4: maestro.inference.v1.LoraConfig
	(*GenerationProgressResponse)(nil), // 5: maestro.inference.v1.GenerationProgressResponse
	(*CancelRequest)(nil),              // 6: maestro.inference.v1.CancelRequest
	(*CancelResponse)(nil),             // 7: maestro.inference.v1.CancelResponse
	(*AudioTranscriptionRequest)(nil),  // 8: maestro.inference.v1.AudioTranscriptionRequest
	(*TranscriptionResponse)(nil),      // 9: maestro.inference.v1.TranscriptionResponse
	(*AudioSegment)(nil),               // 10: maestro.inference.v1.AudioSegment
	(*PromptEnhanceRequest)(nil),       // 11: maestro.inference.v1.PromptEnhanceRequest
	(*PromptEnhanceResponse)(nil),      // 12: maestro.inference.v1.PromptEnhanceResponse
	(*GpuTelemetryRequest)(nil),        // 13: maestro.inference.v1.GpuTelemetryRequest
	(*GpuTelemetryResponse)(nil),       // 14: maestro.inference.v1.GpuTelemetryResponse
}
var file_inference_proto_depIdxs = []int32{
	1,  // 0: maestro.inference.v1.ListModelsResponse.models:type_name -> maestro.inference.v1.ModelInfo
	4,  // 1: maestro.inference.v1.MediaGenerationRequest.loras:type_name -> maestro.inference.v1.LoraConfig
	10, // 2: maestro.inference.v1.TranscriptionResponse.segments:type_name -> maestro.inference.v1.AudioSegment
	3,  // 3: maestro.inference.v1.InferenceService.GenerateMedia:input_type -> maestro.inference.v1.MediaGenerationRequest
	6,  // 4: maestro.inference.v1.InferenceService.CancelGeneration:input_type -> maestro.inference.v1.CancelRequest
	8,  // 5: maestro.inference.v1.InferenceService.TranscribeAudio:input_type -> maestro.inference.v1.AudioTranscriptionRequest
	11, // 6: maestro.inference.v1.InferenceService.EnhancePrompt:input_type -> maestro.inference.v1.PromptEnhanceRequest
	13, // 7: maestro.inference.v1.InferenceService.GetGpuTelemetry:input_type -> maestro.inference.v1.GpuTelemetryRequest
	0,  // 8: maestro.inference.v1.InferenceService.ListModels:input_type -> maestro.inference.v1.ListModelsRequest
	5,  // 9: maestro.inference.v1.InferenceService.GenerateMedia:output_type -> maestro.inference.v1.GenerationProgressResponse
	7,  // 10: maestro.inference.v1.InferenceService.CancelGeneration:output_type -> maestro.inference.v1.CancelResponse
	9,  // 11: maestro.inference.v1.InferenceService.TranscribeAudio:output_type -> maestro.inference.v1.TranscriptionResponse
	12, // 12: maestro.inference.v1.InferenceService.EnhancePrompt:output_type -> maestro.inference.v1.PromptEnhanceResponse
	14, // 13: maestro.inference.v1.InferenceService.GetGpuTelemetry:output_type -> maestro.inference.v1.GpuTelemetryResponse
	2,  // 14: maestro.inference.v1.InferenceService.ListModels:output_type -> maestro.inference.v1.ListModelsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
