# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateMedia = channel.unary_stream(
                '/maestro.inference.v1.InferenceService/GenerateMedia',
                request_serializer=inference__pb2.MediaGenerationRequest.SerializeToString,
                response_deserializer=inference__pb2.GenerationProgressResponse.FromString,
                _registered_method=True)
        self.CancelGeneration = channel.unary_unary(
                '/maestro.inference.v1.InferenceService/CancelGeneration',
                request_serializer=inference__pb2.CancelRequest.SerializeToString,
                response_deserializer=inference__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.TranscribeAudio = channel.unary_unary(
                '/maestro.inference.v1.InferenceService/TranscribeAudio',
                request_serializer=inference__pb2.AudioTranscriptionRequest.SerializeToString,
                response_deserializer=inference__pb2.TranscriptionResponse.FromString,
                _registered_method=True)
        self.EnhancePrompt = channel.unary_unary(
                '/maestro.inference.v1.InferenceService/EnhancePrompt',
                request_serializer=inference__pb2.PromptEnhanceRequest.SerializeToString,
                response_deserializer=inference__pb2.PromptEnhanceResponse.FromString,
                _registered_method=True)
        self.GetGpuTelemetry = channel.unary_unary(
                '/maestro.inference.v1.InferenceService/GetGpuTelemetry',
                request_serializer=inference__pb2.GpuTelemetryRequest.SerializeToString,
                response_deserializer=inference__pb2.GpuTelemetryResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/maestro.inference.v1.InferenceService/ListModels',
                request_serializer=inference__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=inference__pb2.ListModelsResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GenerateMedia(self, request, context):
        """Streaming de progreso de generación de video/imagen
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelGeneration(self, request, context):
        """Cancelar una generación en curso
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TranscribeAudio(self, request, context):
        """Transcripción y análisis de audio
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnhancePrompt(self, request, context):
        """Mejora de prompts con LLM local
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGpuTelemetry(self, request, context):
        """Estado y telemetría de GPU / VRAM
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Catálogo de modelos disponibles (motores, VRAM, disponibilidad)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateMedia': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateMedia,
                    request_deserializer=inference__pb2.MediaGenerationRequest.FromString,
                    response_serializer=inference__pb2.GenerationProgressResponse.SerializeToString,
            ),
            'CancelGeneration': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelGeneration,
                    request_deserializer=inference__pb2.CancelRequest.FromString,
                    response_serializer=inference__pb2.CancelResponse.SerializeToString,
            ),
            'TranscribeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeAudio,
                    request_deserializer=inference__pb2.AudioTranscriptionRequest.FromString,
                    response_serializer=inference__pb2.TranscriptionResponse.SerializeToString,
            ),
            'EnhancePrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.EnhancePrompt,
                    request_deserializer=inference__pb2.PromptEnhanceRequest.FromString,
                    response_serializer=inference__pb2.PromptEnhanceResponse.SerializeToString,
            ),
            'GetGpuTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGpuTelemetry,
                    request_deserializer=inference__pb2.GpuTelemetryRequest.FromString,
                    response_serializer=inference__pb2.GpuTelemetryResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=inference__pb2.ListModelsRequest.FromString,
                    response_serializer=inference__pb2.ListModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'maestro.inference.v1.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('maestro.inference.v1.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/maestro.inference.v1.InferenceService/GenerateMedia',
            inference__pb2.MediaGenerationRequest.SerializeToString,
            inference__pb2.GenerationProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelGeneration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maestro.inference.v1.InferenceService/CancelGeneration',
            inference__pb2.CancelRequest.SerializeToString,
            inference__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TranscribeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maestro.inference.v1.InferenceService/TranscribeAudio',
            inference__pb2.AudioTranscriptionRequest.SerializeToString,
            inference__pb2.TranscriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnhancePrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maestro.inference.v1.InferenceService/EnhancePrompt',
            inference__pb2.PromptEnhanceRequest.SerializeToString,
            inference__pb2.PromptEnhanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGpuTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maestro.inference.v1.InferenceService/GetGpuTelemetry',
            inference__pb2.GpuTelemetryRequest.SerializeToString,
            inference__pb2.GpuTelemetryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/maestro.inference.v1.InferenceService/ListModels',
            inference__pb2.ListModelsRequest.SerializeToString,
            inference__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
